# =============================================================================
# Help System
# =============================================================================

.DEFAULT_GOAL := help

help:
	@echo ""
	@echo "Fintu Tracking - Development Commands"
	@echo "======================================"
	@echo ""
	@echo "Usage: make <target>"
	@echo ""
	@echo "Development:"
	@echo "  make dev                 Start development servers (background)"
	@echo "  make backend-dev         Run backend server in foreground"
	@echo "  make frontend-dev        Run frontend server in foreground"
	@echo "  make setup               Initial project setup"
	@echo "  make install             Install all dependencies"
	@echo "  make stop                Stop all servers"
	@echo "  make stop-backend        Stop backend server"
	@echo "  make stop-frontend       Stop frontend server"
	@echo "  make restart             Restart all servers"
	@echo "  make restart-backend     Restart backend server"
	@echo "  make restart-frontend    Restart frontend server"
	@echo ""
	@echo "Port Management:"
	@echo "  netstat-ports       Show port status"
	@echo "  kill-port PORT=xxx  Kill process on specific port"
	@echo "  check-port-available PORT=xxx  Check if port is free"
	@echo "  ensure-ports-free   Kill processes on dev ports"
	@echo ""
	@echo "Build & Quality:"
	@echo "  build               Build production backend binary"
	@echo "  build-frontend      Build Next.js frontend"
	@echo "  build-all           Build both backend and frontend"
	@echo "  clean               Remove build artifacts"
	@echo "  clean-frontend      Clean frontend build artifacts"
	@echo "  fmt                 Format Go code"
	@echo "  vet                 Run go vet"
	@echo "  lint                Run golangci-lint"
	@echo "  lint-frontend       Run ESLint on frontend"
	@echo "  check               Run all quality checks"
	@echo ""
	@echo "Testing:"
	@echo "  test                Run all Go tests"
	@echo "  test-verbose        Run tests with verbose output"
	@echo "  test-coverage       Generate test coverage report"
	@echo "  test-short          Run short tests only"
	@echo "  test-unit           Run unit tests only"
	@echo "  test-api            Run API tests only"
	@echo ""
	@echo "Validation:"
	@echo "  make health-check       Check backend health endpoint"
	@echo "  make open-frontend      Open frontend in default browser"
	@echo "  make validate-app       Health check + open browser + show URLs"
	@echo ""
	@echo "Dependencies:"
	@echo "  deps                Download Go dependencies"
	@echo "  deps-frontend       Install frontend dependencies"
	@echo "  deps-all            Install all dependencies"
	@echo ""

help-short:
	@echo "Quick Commands:"
	@echo "  make dev        - Start development servers"
	@echo "  make stop       - Stop all servers"
	@echo "  make restart    - Restart all servers"
	@echo "  make check      - Format, vet, lint"
	@echo "  make build      - Build application"
	@echo "  make help       - Show full help"
	@echo ""
