# =============================================================================
# Help System
# =============================================================================

.DEFAULT_GOAL := help

help:
	@echo ""
	@echo "Fintu Tracking - Development Commands"
	@echo "======================================"
	@echo ""
	@echo "Usage: make <target>"
	@echo ""
	@echo "Development:"
	@echo "  make dev                 Start all 3 dev servers (backend :$(BACKEND_PORT), frontend :$(FRONTEND_PORT), marketing :$(MARKETING_PORT))"
	@echo "  make restart             Restart all 3 servers (fast — skips install/check-env)"
	@echo "  make backend-dev         Run backend server in foreground"
	@echo "  make frontend-dev        Run frontend server in foreground"
	@echo "  make marketing-dev       Run marketing server in foreground"
	@echo "  make setup               Initial project setup (all 3 projects)"
	@echo "  make install             Install all dependencies (use FORCE_INSTALL=1 to bypass stamp cache)"
	@echo "  make ensure-deps         Install deps only if lockfiles changed"
	@echo "  make stop                Stop all servers"
	@echo "  make stop-backend        Stop backend server"
	@echo "  make stop-frontend       Stop frontend server"
	@echo "  make stop-marketing      Stop marketing server"
	@echo ""
	@echo "Port Management:"
	@echo "  netstat-ports       Show port status"
	@echo "  kill-port PORT=xxx  Kill process on specific port"
	@echo "  check-port-available PORT=xxx  Check if port is free"
	@echo "  ensure-ports-free   Kill processes on dev ports"
	@echo ""
	@echo "Build & Quality:"
	@echo "  build               Build production backend binary"
	@echo "  build-frontend      Build Next.js frontend"
	@echo "  build-all           Build both backend and frontend"
	@echo "  clean               Remove build artifacts"
	@echo "  clean-frontend      Clean frontend build artifacts"
	@echo "  fmt                 Format Go code"
	@echo "  vet                 Run go vet"
	@echo "  lint                Run golangci-lint"
	@echo "  lint-frontend       Run ESLint on frontend"
	@echo "  check               Run all quality checks"
	@echo ""
	@echo "Marketing (Astro):"
	@echo "  make marketing-dev       Start Astro dev server on :$(MARKETING_PORT)"
	@echo "  make marketing-build      Build marketing site to marketing/dist/"
	@echo "  make marketing-test       Run marketing tests (vitest)"
	@echo "  make marketing-check      Run astro check (type check)"
	@echo "  make marketing-clean      Clean marketing build artifacts"
	@echo ""
	@echo "Testing:"
	@echo "  test                Run backend (go test -race) and frontend (pnpm test)"
	@echo "  test-all            Same as test"
	@echo "  test-verbose        Run Go tests with verbose output"
	@echo "  test-coverage       Generate test coverage report"
	@echo "  test-short          Run short tests only"
	@echo "  test-unit           Run unit tests only"
	@echo "  test-api            Run API tests only"
	@echo ""
	@echo "Validation:"
	@echo "  make health-check       Check backend health endpoint"
	@echo "  make open-frontend      Open frontend in default browser"
	@echo "  make validate-app       Health check + open browser + show URLs"
	@echo ""
	@echo "Dependencies:"
	@echo "  deps                Download Go dependencies"
	@echo "  deps-frontend       Install frontend dependencies"
	@echo "  deps-marketing      Install marketing dependencies"
	@echo "  deps-all            Install all dependencies (backend + frontend + marketing)"
	@echo ""
	@echo "Environment Variables:"
	@echo "  NO_AIR=1            Skip air (Go hot reload) and use 'go run' directly"
	@echo "                      Useful when inotify is exhausted (e.g. EMFILE 'too many open files')"
	@echo "  FORCE_INSTALL=1     Bypass the install stamp cache and reinstall all dependencies"
	@echo ""
	@echo "Headroom (optional AI context compression):"
	@echo "  make headroom-install    Install headroom via uv"
	@echo "  make headroom-uninstall  Remove headroom"
	@echo "  make headroom-doctor     Verify headroom installation"
	@echo "  make headroom-mcp        Register headroom MCP server with Claude Code"
	@echo "  make headroom-learn      Mine sessions and write CLAUDE.local.md"
	@echo "  make headroom-proxy      Start headroom proxy on :$(HEADROOM_PORT)"
	@echo ""

help-short:
	@echo "Quick Commands:"
	@echo "  make dev        - Start development servers"
	@echo "  make stop       - Stop all servers"
	@echo "  make restart    - Restart all servers"
	@echo "  make check      - Format, vet, lint"
	@echo "  make test       - Backend + frontend tests"
	@echo "  make build      - Build application"
	@echo "  make help       - Show full help"
	@echo ""
